# Stage 1: Build the Go binary
FROM golang:1.22 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum, then download dependencies
COPY go.mod go.sum ./
RUN go mod tidy

# Copy the source code and build the Go binary
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/metric-simulator cmd/metric-simulator/main.go

# Stage 2: Create a minimal image with the compiled binary
FROM alpine:latest


# Copy the compiled binary from the builder image
COPY --from=builder /bin/metric-simulator /bin/metric-simulator

# Set ENTRYPOINT and allow for passing flags
ENTRYPOINT ["/bin/metric-simulator"]
CMD []  # Empty CMD allows runtime flags to be passed
